config/routes.rb
Rails.application.routes.draw do
  root 'top#index'
  resources :blogs
  get 'blogs', to: 'blogs#index'
  get 'blogs/new', to: 'blogs#new'
  post '/blogs', to: 'blogs#create'
  get 'top' => 'top#index'
  get 'content' => 'content#new'
  post 'content' => 'content#new'
  post 'confirm' => 'content#confirm'
  post 'thanks' => 'content#thanks'
  get 'detail' => 'content#detail'

end

app/models/blog.rb
class Blog < ActiveRecord::Base
end

app/models/content.rb
class Content < ActiveRecord::Base
    validates :name, presence: true
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
    validates :email, format: {with: VALID_EMAIL_REGEX}, unless: "email.empty?"
    validates :email, presence: true
    validates :content,presence: true
    validates :title,presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :set_blog, only: [:show, :edit, :update, :destroy]

  # GET /blogs
  # GET /blogs.json
  def index
    @blogs = Blog.all
  end

  # GET /blogs/1
  # GET /blogs/1.json
  def show
  end

  # GET /blogs/new
  def new
    @blog = Blog.new
  end

  # GET /blogs/1/edit
  def edit
  end

  # POST /blogs
  # POST /blogs.json
  def create
    @blog = Blog.new(blog_params)

    respond_to do |format|
      if @blog.save
        format.html { redirect_to @blog, notice: 'Blog was successfully created.' }
        format.json { render :show, status: :created, location: @blog }
      else
        format.html { render :new }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /blogs/1
  # PATCH/PUT /blogs/1.json
  def update
    respond_to do |format|
      if @blog.update(blog_params)
        format.html { redirect_to @blog, notice: 'Blog was successfully updated.' }
        format.json { render :show, status: :ok, location: @blog }
      else
        format.html { render :edit }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /blogs/1
  # DELETE /blogs/1.json
  def destroy
    @blog.destroy
    respond_to do |format|
      format.html { redirect_to blogs_url, notice: 'Blog was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_blog
      @blog = Blog.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def blog_params
      params.require(:blog).permit(:title, :content)
    end
end

app/controllers/content_controller.rb
class ContentController < ApplicationController
    before_action :set_blog, only: [:show, :edit, :update, :destroy]
    #before_filter :authenticate_user!
    def new 
        @content =  Content.new
        if params[:back]
        @content = Content.new(confirm_params)
        end
    end
    def confirm
        @content = Content.new(confirm_params)
        if @content.valid? # if true
            render action: 'confirm'
       elsif params[:back] # back page data remain
        render action: 'new'
        else 
           @content.save
            render action: 'new'
        end
    end
    def thanks
        @content = Content.new(confirm_params)
        @content.save
        #NoticeMailer.sendmail_confirm(@entry).deliver
    end
    def detail
        @content = Content.all
    end
    private  #protect hacking
    def confirm_params
       params.require(:content).permit(:name, :email, :content, :title) 
      
    end
end

app/controllers/top_controller.rb
class TopController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/content_helper.rb
module ContentHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/views/blogs/_form.html.erb
<%= form_for(@blog) do |f| %>
  <% if @blog.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@blog.errors.count, "error") %> prohibited this blog from being saved:</h2>

      <ul>
      <% @blog.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_area :content %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/blogs/edit.html.erb
<h1>Editing Blog</h1>

<%= render 'form' %>

<%= link_to 'Show', @blog %> |
<%= link_to 'Back', blogs_path %>

app/views/blogs/index.html.erb
<h1>Blog一覧</h1>
<table>
    <tr>
       <td>Title</td> 
       <td>Content</td> 
    </tr>
    <% @blogs.each do |blog| %>
        <tr>
            <td><%= blog.title %></td>
            <td><%= blog.content %></td>
        </tr>
    <% end %>
</table>
<br><%= link_to 'ブログを投稿する', new_blog_path,{:style=>'color:#FFFFFF;'} %>

app/views/blogs/new.html.erb
<h1>New Blog</h1>

<%= render 'form' %>

<%= link_to 'Back', blogs_path,{:style=>'color:#FFFFFF;'}%>

app/views/blogs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @blog.title %>
</p>

<p>
  <strong>Content:</strong>
  <%= @blog.content %>
</p>

<%= link_to 'Edit', edit_blog_path(@blog) %> |
<%= link_to 'Back', blogs_path %>

app/views/content/confirm.html.erb
<style>
    .width {
        width: 150px;
    }
    table tr td {
        padding-top: 10px;
    }
</style>
<div class="container">
    <table>
    <%= form_for @content, url: thanks_path do |f| %>
    <tr>
     <td class="width">件名「タイトル』</td>
     <td><%= f.text_field :title %></td>
     
     </tr>
    <tr>
     <td class="width">名前</td>
     <td><%= f.text_field :name %></td>
     </tr>
     <tr>
         <td class="width">メールアドレス</td>
        <td><%= f.text_field :email %></td>
      </tr>
      <tr>
          <td class="width">お問い合わせ内容</td>
       <td><%= f.text_area :content %></td>
       </tr>
   </table>
  <p class="align"><%= f.submit '保存', :class => 'button' %></p>
<% end %>
<%= form_for @content, url: content_path do |f| %>
     <p class="align"><%= f.submit '戻る',:name =>'back', :class => 'button' %></p>
     <%= f.hidden_field :title %>
     <%= f.hidden_field :name %>
     <%= f.hidden_field :email %>
     <%= f.hidden_field :content %>
    
<% end %>
</div>

app/views/content/detail.html.erb
<style>
    table tr td {
        min-width:150px; 
    }
    table tr td{
        text-align:center;
    }
</style>

<div class="container">
    <h3 style="color:#9966ff">お問い合わせ一覧</h3>
    <hr class="colorgraph">
    <% @content.each do |i| %>
        <table>
            <tr>
                <td><span style="color:#9966ff">件名:</span></td>
                <td><%= i.title %><br/></td>
            </tr>
            <tr>
                <td><span style="color:#9966ff">名前:</span></td>
                <td><%= i.name %><br/></td>
            </tr>
            <tr> 
                <td><span style="color:#9966ff">お問い合わせ内容:</span></td>
                <td><p><%= simple_format(i.content) %></td>
            </tr> 
            <tr>
                <td><span style="color:#9966ff">日時:</span></td>
                <td><%= i.created_at %></td>
            </tr>
            <tr>
                <td><span style="color:#9966ff">メール:</span></td>
                <td><%= i.email %></td>
            </tr>
        
         </table>
         <hr style="width:100%;background-color:#009933;height:1px;">
        
         
         
    <% end %>
            
           
        
        
        
    
    
    

</div>

app/views/content/login.html.erb
<body class="body_index">
    
</body>

app/views/content/new.html.erb
<style>
    .width {
        width: 150px;
    }
    table tr td {
        padding-top:10px;
    }
</style>
<div class="container">
    <% if @content.errors.any? %>
    <div class="need"  style="list-style:none;">
       <ul> <% @content.errors.full_messages.each do |message| %>
     <li style="list-style:none;"> <h3><%= message %></h3></li>
      </ul>
        <% end %> 
    </div>
    <% end %>
    <%= form_for @content, url: confirm_path do |f| %>
<table>
    <tr>
        <td class="width">件名『タイトル』<span class="need">(*)</span></td>
        <td><%= f.text_field :title %></td>
    </tr>
    <tr>
         <td class="width">名前<span class="need">(*)</span></td>
         <td><%= f.text_field :name %></td>
    </tr>
    <tr>
        <td class="width">メールアドレス<span class="need">(*)</span></td>
         <td><%= f.text_field :email %></td>
    </tr>
    <tr>
        <td class="width">お問い合わせ内容</td>
        <td><%= f.text_area :content %></td> 
    </tr>
</table>
<p class="align"><%= f.submit '確認', :class => 'button' %></p>
 <% end %>
</div>

app/views/content/thanks.html.erb
<div class="container">
<h4>お問い合わせ完了メーイルを送ります。チェックしてください。</h4>
<h3>完了です。ありがとうございました。</h3>

<p class="button"><%= link_to 'トップページ', top_path ,{:style=>'color:#FFFFFF;'} %></p>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="ja">
<head>
  <meta charset="UTF-8">
  <title>Achieve1</title>
  <meta name="viewport" content="width=device-width">
  <!--link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css"-->
  <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
  <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
        <nav class="navbar navbar-inverse">
          <div class="container-fluid">
            <div class="navbar-header">
              <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>                        
              </button>
              <a class="navbar-brand">トップページ</a>
               <a><%= link_to 'お問い合わせ',content_path, {:style=>'color:#FFFFFF;'} %></a>
            </div>
            
                
               
                
             
          </div>
        </nav>
        <%= yield %>

</body>
</html>

app/views/top/index.html.erb
<h1>すべての人にテクノロジー</h1>
<p>DiveIntoCode</p>
<div class="boxA">
    <div class="box1"> 
    <div class="site"> 
    <h1><a href="#">Dive into Code by HmweMya</a></h1> 
    </div> 
    </div>
    <div class="box2"> 
    <nav class="menu"> 
    <ul> 
    <li><%= link_to "Top", root_path %></li> 
    <li><a href="#">お問い合わせ</a></li> 
    </ul> 
    </nav> 
    </div> 
    <div class="box3"> 
    <%= image_tag("Header.png", class: "topimg") %> 
    </div>
    <div class="box4"> 
    <div class="box4-1"> 
    <div class="merit"> 
    <a href="#">
    <i class="fa fa-heart"></i>
    <h1>経験ゼロの初心者向け</h1> 
    <p>全10回講座の課題解決型プログラム。経験ゼロからWebエンジニアになっていただきます。</p> 
    </a>
    </div> 
    </div> 
    <div class="box4-2"> 
    <div class="merit"> 
    <a href="#">
    <i class="fa fa-television"></i>
    <h1>オンラインサポート付き</h1> 
    <p>専用のfacebookグループ内やNitrousのコラボレーション機能を経由して随時オンラインサポート</p> 
    </a>
    </div>
    </div> 
    <div class="box4-3"> 
    <div class="merit"> 
    <a href="#">
    <i class="fa fa-connectdevelop"></i>
    <h1>チームで実践「受託開発」</h1> 
    <p>ひとりではなく開発チームを結成し、実ビジネスの受託開発を経験して卒業していただきます。</p> 
    </a>
    </div> 
    </div>
    </div>
    <div class="box5"> 
    <div class="copyright"> 
    <p>Copyright &copy; 2015 Dive into Code All Rights Reserved.</p> 
    </div> 
    </div>
</div>